name: ws_app_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  #Get 状态管理，路由，依赖管理，国际化以及主题变更
  get: ^3.26.0
  #网络请求
  dio: ^3.0.10
  #本地数据存储
  shared_preferences: ^0.5.7+3
  #权限申请
  permission_handler: ^5.1.0+2
  #包信息
  package_info: ^2.0.0
  #设备信息
  device_info: ^2.0.0
  #Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: ^0.3.3
  #网络监测
  connectivity: ^3.0.2
  #uuid
  uuid: ^2.2.2

  #tabbar
  persistent_bottom_nav_bar: ^4.0.2
  #闪屏页
  # flutter_native_splash: any
  #官方webview插件
  # webview_flutter: 
  #   path: plugins/webview_flutter
  #loading组件
  flutter_spinkit: ^4.1.2+1
  #圆形、直线进度条
  percent_indicator: ^3.0.1
  #网络图片加载组件 类似SDWebImage
  cached_network_image: ^2.3.3
  extended_image: any
  #上下拉刷新
  pull_to_refresh: ^1.6.4
  #轮播图
  flutter_swiper: ^1.1.6
  # 类iOS侧滑菜单
  flutter_slidable: ^0.5.7
  # 谁用谁闪亮
  # shimmer: ^1.1.2
  # 通讯录列表
  azlistview: ^2.0.0-nullsafety.0
  #图片选择器
  image_picker: ^0.6.7+22
  wechat_assets_picker: any
  #类似微信拍摄的相机
  # wechat_camera_picker: ^2.0.0-nullsafety.4
  #图片浏览查看
  photo_view: ^0.11.1
  #图片保存到本地相册
  image_gallery_saver: ^1.6.8
  #视频播放器
  chewie: ^0.12.2
  video_player: ^1.0.1
  # 验证码输入框1`
  pin_code_text_field: ^1.8.0
  #选择器
  flutter_picker: ^2.0.1
  flutter_pickers: ^2.0.1
  #loading、toast
  flutter_easyloading: ^2.2.2
  # 小红点 https://pub.flutter-io.cn/packages/badges
  badges: ^1.2.0
  # 处理键盘事件 https://pub.flutter-io.cn/packages/keyboard_actions
  keyboard_actions: ^3.3.1+1
  # gif图片
  flutter_gifimage: ^1.0.1
  # 吸顶头部
  flutter_sticky_header: ^0.5.0
  # 图片加载loading
  loading: ^1.0.2
  # 录音插件
  flutter_plugin_record: ^0.3.5
  # 文件选择器
  file_picker: ^2.1.7
  # 视频压缩
  video_compress: ^3.0.0
  # 图片压缩
  flutter_native_image: ^0.0.5+3
  # 路径转换工具
  flutter_absolute_path: ^1.0.6
  # 加载html文本
  flutter_html: 
    path: plugins/flutter_html
  # 点赞按钮
  like_button: ^2.0.0
  # 列表滚动到指定行
  # scrollable_positioned_list: ^0.1.10
  # 文本展开收起
  expandable_text: ^1.3.2
  auto_size_text: ^3.0.0-nullsafety.0
  # 列表动画
  # flutter_staggered_animations: ^1.0.0
  # 气泡组件
  flutter_bubble: ^0.0.1
  # bubble: any

  #打开第三方应用
  url_launcher: ^5.7.10
  #分享
  sharesdk_plugin: ^1.2.9
  #扫码
  flutter_qr_reader: 1.0.3
  #极光推送
  jpush_flutter: ^0.6.3
  #高德地图
  amap_map_fluttify: ^0.30.1
  # amap_flutter_map: ^1.0.2
  #腾讯云IM
  tencent_im_sdk_plugin: ^1.0.20
  #bugly
  flutter_bugly: ^0.3.1
  #易观方舟flutter插件
  argo_flutter_plugin: ^1.0.0
  #七牛云插件
  qiniu_flutter_sdk: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/car/
    - assets/images/chekong/
    - assets/images/door_lock/
    - assets/images/circle/
    - assets/images/common/
    - assets/images/enjoy/
    - assets/images/guide/
    - assets/images/login/
    - assets/images/mine/
    - assets/images/splash/
    - assets/images/tabbar/
    - assets/images/wow/
    - assets/static/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
