//静态存储常量key
const String SID_KEY = 'SID';
const String REGISTRATIONID = 'REGISTRATIONID';
const String FIRSTLAUNCH = 'FIRSTLAUNCH';
const String REGISTRATIONID_SUCCESS = 'REGISTRATIONID_SUCCESS';
const String USER_INFO = 'USER_INFO';
